### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/DFNet#1]
Hi, thanks for sharing your great work. However, when I tried to run the code, I didn't find the definition of `FeatureNet()`.
https://github.com/ActiveVisionLab/DFNet/blob/18fde99929335a7fd4e450a22c996c408754e3fb/script/train.py#L109

**Comment by chenusc11** [comment]
Great thanks for pointing out this issue. Sorry for the confusion. This was my legacy code for previous experiments which SHOULD be removed. I have just updated a fix [here](https://github.com/ActiveVisionLab/DFNet/commit/45880b7e6230aa278ea0da7a33110bbf396de71c).

In short, train.py is for training the (DFNet<sub>dm</sub>) model with a pre-trained DFNet/APR model.
In this case, --pretrain_model_path requires a valid PATH to the pre-trained model.

Please checkout [config_dfnetdm.txt](https://github.com/ActiveVisionLab/DFNet/blob/main/script/config_dfnetdm.txt) for my current config files.

Let me know if you have any further questions :)

**Comment by LZL-CS** [comment]
Hi @chenusc11, thanks for your reply, I will try it.
