### ISSUE TITLE
Question about "Qualitative comparison on the 7-Scenes dataset" in Fig. 7

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/DFNet#11]
Hi, when I tried to visualize the camera poses like your results in `Fig.7`, I found that your visualization results are quite different from raw data in 7Scenes, such as scene `Chess-seq-03`:
Your visualization result is:
<img width="1500" alt="image" src="https://github.com/ActiveVisionLab/DFNet/assets/54640259/c933c781-e311-40a0-9e66-b610210c19ad">

While I visualize it from raw 7Scenes camera poses of  `Chess-seq-03`, and I get the result as below:
![image](https://github.com/ActiveVisionLab/DFNet/assets/54640259/8a16f378-ad7e-42fd-9c97-f5d66c4cf288)

I appreciate any help you can provide to this issue!

**Comment by chenusc11** [comment]
Hi, the visualization is done in OpenGL convention (I think). You could apply the code here to the raw data to get our visualized plot. Or, if you want to visualize DFNet's predicted trajectory in same convention as the raw data, just simply reverse the process of fix_coord().

https://github.com/ActiveVisionLab/DFNet/blob/1389760f770851a77e601af1312f19fe065bd185/dataset_loaders/load_7Scenes.py#L279

**Comment by LZL-CS** [comment]
> Hi, the visualization is done in OpenGL convention (I think). You could apply the code here to the raw data to get our visualized plot. Or, if you want to visualize DFNet's predicted trajectory in same convention as the raw data, just simply reverse the process of fix_coord().
> 
> https://github.com/ActiveVisionLab/DFNet/blob/1389760f770851a77e601af1312f19fe065bd185/dataset_loaders/load_7Scenes.py#L279

Hi @chenusc11, I got it and thanks for your prompt reply!
