### ISSUE TITLE
Question about how to visualize feature map  in the paper?

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/DFNet#14]
Hi @chenusc11, thanks for your awesome work. May I know how to visualize the feature map in the paper below:
<img width="716" alt="image" src="https://github.com/ActiveVisionLab/DFNet/assets/54640259/5a2ab968-1fa7-495c-8dd5-71cef38d2139">
I appreciate any help you can provide!

**Comment by chenusc11** [comment]
Hi, you can save the features by normalizing feature values to (0,1) or (0,255) and save them using matplotlib

**Comment by LZL-CS** [comment]
> Hi, you can save the features by normalizing feature values to (0,1) or (0,255) and save them using matplotlib

Got it. Do I need to use the PCA to extract the main componets, e.g., RGB 3-channels, from the feature first and then normalize it for visulization?

**Comment by chenusc11** [comment]
The features are in 128 channels. You could plot one of the channels. I plotted every channel before, the contents look reasonably similar after normalization.
