### ISSUE TITLE
A question about rendering quality

### ISSUE THREAD

**Issue by shenyehui** [ActiveVisionLab/DFNet#15]
Dear author,

Hello. I have been using your run_nerf.py program to examine the rendering results. However, I have noticed that the images generated by the render_virtual_imgs function for new viewpoints appear somewhat blurry. Could you please advise on how to generate clearer images for new viewpoints?

Thank you！

**Comment by shenyehui** [comment]
![049](https://github.com/ActiveVisionLab/DFNet/assets/48650979/d73b2803-dbfc-45cd-8f77-ea1e7bfded17)
![046](https://github.com/ActiveVisionLab/DFNet/assets/48650979/70f974b3-70b7-4668-9c2b-dbb41084beef)

**Comment by shenyehui** [comment]
Dear author, many images generated by random_view_synthesis appear to be somewhat blurry. Will this affect the model's performance? How can the parameters be adjusted to generate clearer images?

**Comment by chenusc11** [comment]
Hi, from the look of it, it might render the views with camera positions that are lower than the ground. To ensure "clear images" are rendered, please consider reducing --rvs_trans values or setting a lower bound for the height of the camera position to reduce the "blurry images."

Overall, nerf only encodes scene details available in the training views. It is normal that if the camera position is "too out of range," the artifacts will appear. Currently, there are several papers on reducing this phenomenon.

**Comment by shenyehui** [comment]
> Hi, from the look of it, it might render the views with camera positions that are lower than the ground. To ensure "clear images" are rendered, please consider reducing --rvs_trans values or setting a lower bound for the height of the camera position to reduce the "blurry images."
> 
> Overall, nerf only encodes scene details available in the training views. It is normal that if the camera position is "too out of range," the artifacts will appear. Currently, there are several papers on reducing this phenomenon.

Thank you！
