### ISSUE TITLE
The question about internal parameters of the rendering image

### ISSUE THREAD

**Issue by shenyehui** [ActiveVisionLab/DFNet#16]
Dear author, I have generated some images using your code. How can I obtain the internal parameters (fx, fy, cx, cy) of the generated images? Is fx=fy=f? How can I calculate cx and cy? The hwf of the image generated using my code is [240, 427, 372.0].

**Comment by chenusc11** [comment]
Hi, sorry for the late reply. Not sure if I understood your problem correctly. Maybe just assume the center of the image as cx, cy? Yes, you could assume fx=fy=f.

**Comment by shenyehui** [comment]
Thank you!
