### ISSUE TITLE
How to Visualize

### ISSUE THREAD

**Issue by illusion322** [ActiveVisionLab/DFNet#19]
I want a sample visualization like Figure 7, but I don't know how to get the

**Comment by chenusc11** [comment]
Hi, the Figure 7 is using matplotlib to visualize poses. The upper plot are predicted translational pose (red) vs. GT translational  pose (green). The lower color bar are rotational errors. Nowadays, you probably can use chatgpt to help you generating a nice looking figure quickly :)

**Comment by illusion322** [comment]
Hi, can you be more detailed, I'm just looking at this project and I don't really understand the workflow yet, but I do need a way to visualize it, is there any way to get the bit position data quickly?

**Comment by chenusc11** [comment]
Try this:
https://github.com/ActiveVisionLab/DFNet/blob/2c8fa7e324f8d17352ed469a8b793e0167e4c592/script/dm/pose_model.py#L33C5-L33C13

**Comment by chenusc11** [comment]
Close the issue for now. Feel free to reopen it if needed.
