### ISSUE TITLE
Question about the pipline in the paper

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/DFNet#23]
Hi @chenusc11, I am confused why here you use **GT Pose P** as input rather than use **Predicted Pose** from the PoseNet model as input to NeRF?
![image](https://github.com/ActiveVisionLab/DFNet/assets/54640259/83fb529b-f360-411f-81f5-e7c22f1ac063)

While here you seem to use **Predicted Pose** from the PoseNet model as input to NeRF:
![image](https://github.com/ActiveVisionLab/DFNet/assets/54640259/b471a83d-0903-4c18-82e8-6ad6c788df4f)

**Comment by chenusc11** [comment]
Hi, really sorry for missing this thread. I wasn't aware of this issue until now. I apologize for this.

Figure 2b illustrates a high-level scheme to train the DFNet features. In the training stage, we want to make sure that features of real images and synthetic images (from NeRF) from the **same poses** are **as close as possible**; and features of real and synthetic images from the **different poses** to be **as far as possible**. That is why we input GT poses to do the first task and roll the GT poses to do the second task. This can be found in our triplet loss implementation in the code.

**Comment by LZL-CS** [comment]
> Hi, really sorry for missing this thread. I wasn't aware of this issue until now. I apologize for this.
> 
> Figure 2b illustrates a high-level scheme to train the DFNet features. In the training stage, we want to make sure that features of real images and synthetic images (from NeRF) from the **same poses** are **as close as possible**; and features of real and synthetic images from the **different poses** to be **as far as possible**. That is why we input GT poses to do the first task and roll the GT poses to do the second task. This can be found in our triplet loss implementation in the code.

Hi @chenusc11  Thanks for your reply, I got it. I am closing this issue now.
