### ISSUE TITLE
Question about the world_setup.json data

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/DFNet#5]
Hi, thanks for your work. May I know the derivation of configs in each dataset for 7Scenes and Cambridge (such as **pose_scale**, **pose_scale2**, and **move_all_cam_vec**): 
```
 "pose_scale": 0.3027,
 "pose_scale2": 0.2,
 "move_all_cam_vec": [0.0, 0.0, 0.0] 
```

I really appreciate any help you can provide, thanks!

**Comment by chenusc11** [comment]
Hi, sorry for the late reply. 

This is just my manually set parameter to place the scene objects in the center of the world space for the input pose of the NeRF. I think this makes NeRF easier to learn.

Such transformation of the pose does not affect the output of APR, but only the NeRF input poses.

**Comment by LZL-CS** [comment]
@chenusc11 Happy New Year to you and thanks for your reply. 

If I use my other datasets, how can I calculate these parameters of config, could you give some hints, thanks!

**Comment by LZL-CS** [comment]
> Hi, sorry for the late reply.
> 
> This is just my manually set parameter to place the scene objects in the center of the world space for the input pose of the NeRF. I think this makes NeRF easier to learn.
> 
> Such transformation of the pose does not affect the output of APR, but only the NeRF input poses.

Hi @chenusc11, Are these "pose_scale" and "pose_scale2" obtained by comparing them with the processed colmap data?

**Comment by chenusc11** [comment]
Hi, sorry for the late reply.

I tune the pose by writing a script to visualizing frustum from each camera position and estimates the object centers. This is only a rough estimation manually. If you want to do the same in your dataset, you could also use similar technique.

**Comment by LZL-CS** [comment]
> Hi, sorry for the late reply.
> 
> I tune the pose by writing a script to visualizing frustum from each camera position and estimates the object centers. This is only a rough estimation manually. If you want to do the same in your dataset, you could also use similar technique.

ok, I got it. thanks for your reply, I am closing this issue.
