### ISSUE TITLE
Qustions about camera pose processing

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/DFNet#6]
Hi,

The Cambridge camera pose is processed with complex transformations (fix_coord() function), so I was wondering what tools (or python library) you recommend for camera pose (rotation+translation) visualization to help us understand these transformations?

Thanks in advance!

**Comment by chenusc11** [comment]
Hi, I wrote a script myself. It is easier to implement if you just mimicking ray sampling like NeRF does. For example, sample a batch of rays per camera pose and visualize them using matplotlib or some equivalent tools.

**Comment by LZL-CS** [comment]
got it and thanks for your reply, I am closing this issue.
