### ISSUE TITLE
Question about the model training process

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/DFNet#9]
Hi @chenusc11, in the pipeline of your **DFNet** paper, it seems that you use estimated pose P(hat) for Histogram-assisted NeRFH model to generate a rendered image, which is similar to your previous paper **Direct-PosNet** training process.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/54640259/221403737-d88886ed-44bc-447c-9d8a-b924f472b677.png">

![image](https://user-images.githubusercontent.com/54640259/221403760-fe4beb88-298d-4729-b7b3-907bf820e610.png)

However, in the **DFNet** code, I didn't find any place where you use the estimated pose for Histogram-assisted NeRFH. While in the  **Direct-PosNet** code, you first train a PoseNet for camera pose estimation, then use this pre-trained model for NeRF model. May I know the reason for the difference in training between **DFNet** and **Direct-PosNet**? Maybe I miss something important, hope for your reply.

Kind regards, Thanks!

**Comment by chenusc11** [comment]
Not sure I understand your question. However, DFNet itself could estimate more accurate camera poses than PoseNet. I'm closing the issue for now. If you want to further elaborate on this issue, please feel free to do so.
